window.RULES_DATA = [
{
  "title": "QUY TRÌNH XÉT DUYỆT RÚT TIỀN - TIỀN THƯỞNG UPDATE 30/07/2026",
  "content": "📅 Thời gian áp dụng: 30/07/2025\n\nI. THƯỞNG WEBSITE / THƯỞNG QUAY TRỞ LẠI / RUMMY MATCH (1-3-5-7Đ)\n\n✅ Điều kiện xét duyệt:\n• Hội viên có nạp tiền trong 7 ngày gần đây.\n• Hoàn thành đủ vòng cược.\n• IP/Thiết bị không có dấu hiệu lạm dụng nạp đầu.\n\n→ Có thể xét duyệt rút tiền.\n\n❌ Trường hợp khấu trừ / từ chối:\n• Không nạp tiền trong 7 ngày gần đây sau khi đã yêu cầu nạp.\n• Nhiều tài khoản cùng IP/Thiết bị có dấu hiệu lạm dụng nạp đầu.\n\n📌 Lưu ý:\n• Cần kiểm tra lịch sử chơi trước khi xử lý.\n\n==========================\n\nII. THƯỞNG 500 VÒNG QUAY\n\n1️⃣ Yêu cầu vòng cược\n\nEZ / KA9 / WR / JW / MM / 8GAME / HU / GG / WW / EK7\n• Kênh đầu tư: (Số dư hiện tại + 500) × 5.\n• Kênh không đầu tư: (Số dư hiện tại + 500) × 8.\n\n777IN / 365IN\n• Kênh đầu tư: 500 × 5.\n• Kênh không đầu tư: 500 × 6.\n\nINDIA2026 / GEM7\n• Kênh đầu tư: 500 × 5.\n• Kênh không đầu tư: 500 × 8.\n\n📌 Thành viên không nạp tiền trong 7 ngày:\n• Không phải là trường hợp bất thường.\n• Tiền thưởng đã được bộ phận tặng thưởng kiểm tra điều kiện trước khi cấp thưởng.\n\n2️⃣ Chỉ cần kiểm tra:\n✅ Hoàn thành đủ vòng cược.\n✅ Cược bình thường.\n✅ Không trùng IP/Thiết bị bất thường với cấp dưới.\n✅ Đường dây đại lý bình thường.\n\n→ Có thể xét duyệt rút tiền.\n\n3️⃣ Trường hợp khấu trừ:\n❌ Cược tỷ lệ thấp.\n❌ Tự đánh đối chính mình.\n❌ All-in để chạy vòng cược.\n❌ Đường dây đại lý lạm dụng nạp đầu.\n❌ Nhiều tài khoản cùng số tiền nạp đầu nhằm nhận thưởng.\n\n==========================\n\nIII. KIỂM TRA IP / THIẾT BỊ\n\n📌 Lưu ý:\n• Trùng IP/Thiết bị với ID cũ đã lâu không hoạt động không đồng nghĩa là gian lận.\n• Đại lý lớn có nhiều thành viên chung IP/Thiết bị là trường hợp bình thường nếu có lịch sử chơi thật.\n• Không được chỉ dựa vào IP/Thiết bị để khấu trừ.\n\n📝 Ví dụ:\nCó 10 cấp dưới:\n• 5 cấp dưới từ tháng 5.\n• 5 cấp dưới từ tháng 7.\n\nNếu cấp trên nhận thưởng 500 và chỉ trùng 1 thiết bị với ID từ tháng 5 thì đây là trường hợp bình thường.\n\nNếu đường dây cũ đã bị xử lý, sau này thành viên phát triển cấp dưới mới không liên quan đến IP/Thiết bị của đường dây cũ thì vẫn có thể xem xét bình thường.\n\n==========================\n\n📌 Lưu ý chung:\n• Trường hợp chưa chắc chắn thì hỏi lại cấp trên.\n• Không tự ý xử lý.\n\n==========================\n\n✅ Checklist trước khi duyệt:\n• Đủ vòng cược.\n• Cược bình thường.\n• IP/Thiết bị không có dấu hiệu lạm dụng.\n• Đường dây đại lý bình thường.\n\n➡️ Đáp ứng đầy đủ các điều kiện trên thì có thể xét duyệt rút tiền."
},
{
  "title": "QUY TẮC ÁP DỤNG VÒNG CƯỢC ĐỐI VỚI NỀN TẢNG CHÍNH",
  "content": "📅 Thời gian áp dụng: 11/05/2026\n\nÁp dụng cho: EZ777 / 8GAME / EK7 / KA9 / JW / WR / HU / GG / WW / MM9.\n\n1️⃣ Lần rút tiền thứ 1, 2, 3 (Manual Review)\n• Kênh đầu tư (投放 = FB + GG): 5 lần vòng cược.\n• Kênh không đầu tư (官网、我的、转盘、分销、强更包、SMS): 8 lần vòng cược.\n• Tiền khuyến mãi nạp: nhân 10 lần vòng cược.\n\n📝 Ví dụ:\n• Nạp 100, thưởng 37.\n- Kênh đầu tư: (100 × 5) + (37 × 10) = 870.\n- Kênh không đầu tư: (100 × 8) + (37 × 10) = 1170.\n\n📌 Lưu ý:\n• Cả 3 lần rút đầu tiên đều bắt buộc áp dụng quy tắc 5x hoặc 8x theo kênh.\n• Sau khi xử lý đơn rút đầu tiên phải ghi chú (Remark) cho ID thành viên.\n• Từ lần rút thứ 4 trở đi, nếu thành viên giao dịch bình thường thì có thể xóa ghi chú.\n\n==========================\n\n2️⃣ Quy tắc vòng cược theo hành vi\n\n• Thành viên đã nạp/rút nhiều lần và có hành vi cược bình thường: áp dụng 3x hoặc 5x tùy trường hợp.\n• Thành viên nạp nhỏ nhiều lần trong ngày (100–300): áp dụng 5x hoặc 8x theo kênh.\n• Thành viên chỉ nạp một lần trong ngày (100–300): áp dụng 5x hoặc 8x theo kênh.\n\n==========================\n\n🎯 Kết luận\n• Khách bình thường → 3x – 5x.\n• Khách nạp nhỏ nhiều lần → 5x – 8x.\n• Khách mỗi ngày chỉ nạp 100 → 5x – 8x.\n\n==========================\n\n🎁 Tiền thưởng vòng quay 500\n• Áp dụng yêu cầu vòng cược 5x hoặc 8x tùy theo nguồn kênh."
},
{
  "title": "QUY TẮC ÁP DỤNG VÒNG CƯỢC 777IN / 365IN UPDATE 12/06/2026",
  "content": "📅 Thời gian áp dụng: 12/06/2026\n\nÁp dụng cho: 777IN / 365IN.\n\n1️⃣ Lần rút tiền đầu tiên\n• Kênh đầu tư (投放 = FB + GG): 3 lần vòng cược.\n• Kênh không đầu tư (官网、我的、转盘、分销、强更包、SMS): 6 lần vòng cược.\n\n==========================\n\n2️⃣ Lần rút tiền không phải lần đầu\n(Tính dựa trên tổng số tiền nạp và tổng doanh thu cược của thành viên)\n\n• Kênh đầu tư (投放 = FB + GG): 5 lần vòng cược.\n• Kênh không đầu tư (官网、我的、转盘、分销、强更包、SMS): 6 lần vòng cược.\n\n==========================\n\n📌 Quy tắc xét duyệt\n• Lần rút đầu tiên: kiểm tra theo số tiền nạp của lần rút đầu.\n• Các lần rút tiếp theo: kiểm tra theo tổng số tiền nạp và tổng doanh thu cược của thành viên.\n• Đồng thời kiểm tra IP, thiết bị, lịch sử đặt cược và các dấu hiệu kiểm soát rủi ro theo quy định hiện hành.\n\n==========================\n\n📢 Tiền thưởng vòng quay 500\n• Kênh đầu tư: yêu cầu hoàn thành 5 lần vòng cược.\n• Kênh không đầu tư: yêu cầu hoàn thành 6 lần vòng cược.\n\n==========================\n\n📌 Lưu ý\n• Các quy tắc xét duyệt đã được điều chỉnh.\n• Tất cả các biện pháp kiểm soát rủi ro được áp dụng đồng thời khi xét duyệt.\n• Quy tắc sẽ được theo dõi và đánh giá trong thời gian đầu để tiếp tục tối ưu nếu cần."
},
{
  "title": "QUY TẮC ÁP DỤNG VÒNG CƯỢC INDIA2026 UPDATE 10/07/2026",
  "content": "📅 Thời gian áp dụng: 10/07/2026\n\nÁp dụng cho: INDIA2026.\n\n1️⃣ Rút tiền lần đầu (Thành viên có nạp tiền)\n• Kênh đầu tư (投放 = FB + GG): 3 lần vòng cược.\n• Kênh không đầu tư (官网、我的、转盘、分销、强更包、SMS): 7 lần vòng cược.\n\n==========================\n\n2️⃣ Rút tiền lần đầu (Thành viên chưa nạp tiền)\n• Vòng cược được tính theo số tiền thưởng nhận được.\n• Bản thân thành viên hoặc cấp dưới bắt buộc phải có ít nhất một bên phát sinh nạp tiền.\n• Kênh đầu tư (投放 = FB + GG): 5 lần vòng cược.\n• Kênh không đầu tư (官网、我的、转盘、分销、强更包、SMS): 8 lần vòng cược.\n\n==========================\n\n3️⃣ Rút tiền từ lần thứ 2 trở đi\n• Kiểm tra theo tổng số tiền nạp và tổng doanh thu cược của thành viên.\n• Kênh đầu tư (投放 = FB + GG): 5 lần vòng cược.\n• Kênh không đầu tư (官网、我的、转盘、分销、强更包、SMS): 8 lần vòng cược.\n\n==========================\n\n📢 Tiền thưởng vòng quay 500\n• Kênh đầu tư: yêu cầu hoàn thành 5 lần vòng cược.\n• Kênh không đầu tư: yêu cầu hoàn thành 8 lần vòng cược.\n\n==========================\n\n📌 Lưu ý\n• Thành viên có nạp tiền: áp dụng quy tắc vòng cược theo từng lần rút.\n• Thành viên chưa nạp tiền: tính vòng cược theo số tiền thưởng nhận được.\n• Từ lần rút thứ 2 trở đi, kiểm tra dựa trên tổng số tiền nạp và tổng doanh thu cược của thành viên."
},
{
  "title": "QUY TẮC KIỂM TRA VÒNG CƯỢC GEM7 UPDATE 12/07/2026",
  "content": "📅 Thời gian áp dụng: 12/07/2026\n\nGEM7\n\n1️⃣ Rút tiền lần đầu (Thành viên có nạp tiền)\n• Kênh quảng cáo (投放): 3 lần vòng cược.\n• Kênh không quảng cáo: 7 lần vòng cược.\n\n2️⃣ Rút tiền lần 2 – 3 (Thành viên có nạp tiền)\n• Kênh quảng cáo (投放): 5 lần vòng cược.\n• Kênh không quảng cáo: 8 lần vòng cược.\n\n3️⃣ Rút tiền lần đầu (Thành viên chưa nạp tiền)\n(Tính vòng cược theo giá trị tiền thưởng nhận được)\n• Bản thân hoặc cấp dưới bắt buộc phải có ít nhất 1 bên phát sinh nạp tiền.\n• Kênh quảng cáo (投放): 5 lần vòng cược.\n• Kênh không quảng cáo: 8 lần vòng cược.\n\n4️⃣ Rút tiền lần 4 trở lên\n(Kiểm tra theo tổng số tiền nạp và tổng doanh thu cược của thành viên)\n• Kênh quảng cáo (投放): 5 lần vòng cược.\n• Kênh không quảng cáo: 8 lần vòng cược.\n\n📌 Thay đổi quan trọng (12/07/2026):\n• Đối với các lần rút tiền thứ 1, 2 và 3 của thành viên có nạp tiền, bắt buộc tính vòng cược dựa trên chính đơn nạp tiền tương ứng với lần rút đó.\n• Không được cộng dồn tổng tiền nạp để tính vòng cược ở 3 lần rút đầu.\n• Chỉ từ lần rút tiền thứ 4 trở đi mới kiểm tra theo tổng số tiền nạp và tổng doanh thu cược của thành viên.\n\n📝 Ví dụ:\n• Thành viên nạp 100 và thực hiện rút tiền lần đầu.\n→ Kênh quảng cáo: (100 + Khuyến mãi) × 3.\n→ Kênh không quảng cáo: (100 + Khuyến mãi) × 7.\n\n• Thành viên nạp lần thứ 2 và thực hiện rút tiền lần thứ 2.\n→ Chỉ lấy số tiền của lần nạp thứ 2 để tính vòng cược theo quy định.\n\n• Chỉ từ lần rút tiền thứ 4 trở đi mới lấy tổng tiền nạp và tổng doanh thu cược để đối chiếu.\n\n📌 Lưu ý:\n• Thành viên có nạp tiền: áp dụng quy tắc vòng cược theo từng lần rút tương ứng.\n• Thành viên chưa nạp tiền: tính vòng cược theo giá trị tiền thưởng nhận được.\n• Toàn bộ quy trình xét duyệt và kiểm soát rủi ro của GEM7 áp dụng theo quy định này kể từ ngày 12/07/2026."
},
{
  "title": "HƯỚNG DẪN TRÌNH BÀY BÀI THI 📌",
  "content": "📌 MẪU TRÌNH BÀY\n==========================\n\n*Căn cứ đánh giá:\n...\n\n*Nhận định rủi ro:\n...\n\n*Đề xuất xử lý:\n...\n\n==========================\n\n📖 VÍ DỤ 1\n\n*Căn cứ đánh giá:\nThành viên nhận thưởng 500 vòng quay, chưa hoàn thành đủ vòng cược.\n\n*Nhận định rủi ro:\nChưa đáp ứng điều kiện rút tiền theo quy định.\n\n*Đề xuất xử lý:\nTừ chối lệnh rút tiền và yêu cầu hoàn thành thêm 03 lần vòng cược.\n\n==========================\n\n📖 VÍ DỤ 2\n\n*Căn cứ đánh giá:\nThành viên nhận thưởng nhóm, phát hiện trùng IP/thiết bị với tài khoản cấp dưới.\n\n*Nhận định rủi ro:\nCó dấu hiệu lạm dụng thưởng nhóm.\n\n*Đề xuất xử lý:\nKhấu trừ thưởng nhóm và báo QC khóa quyền nhận hoa hồng đại lý.\n\n==========================\n\n📖 VÍ DỤ 3\n\n*Căn cứ đánh giá:\nThành viên nạp tiền và đặt cược bình thường, đã hoàn thành đủ vòng cược.\n\n*Nhận định rủi ro:\nKhông phát hiện dấu hiệu bất thường.\n\n*Đề xuất xử lý:\nCó thể xét duyệt rút tiền bình thường.\n\n==========================\n\n📖 VÍ DỤ 4\n\n*Căn cứ đánh giá:\nThành viên có hành vi cược All-in ngay sau khi nạp tiền.\n\n*Nhận định rủi ro:\nCó dấu hiệu vi phạm quy định cược.\n\n*Đề xuất xử lý:\nKhấu trừ tiền thưởng, hoàn trả tiền nạp. Nếu tiếp tục vi phạm, báo QC khóa tài khoản.\n\n==========================\n\n📖 VÍ DỤ 5\n\n*Căn cứ đánh giá:\nThành viên có nhiều đơn rút tiền thất bại liên tiếp, nạp tiền và đặt cược bình thường.\n\n*Nhận định rủi ro:\nKhông phát hiện dấu hiệu lạm dụng, khả năng liên quan đến lỗi kênh thanh toán.\n\n*Đề xuất xử lý:\nBáo QC và bộ phận Đào tạo thông báo cho phía Tài vụ kiểm tra, tạm thời không tiếp tục xuất đơn.\n\n==========================\n\n💡 Lưu ý:\n• Trình bày đầy đủ 03 phần: Căn cứ đánh giá – Nhận định rủi ro – Đề xuất xử lý.\n• Nội dung ngắn gọn, rõ ràng và bám sát quy định hiện hành.\n• Không đưa ra kết luận khi chưa có đủ căn cứ.\n\n💯 Chúc tất cả mọi người hoàn thành bài kiểm tra với kết quả tốt! Chúc mọi người đạt kết quả thật cao! 🚀"
},
{
"title": "QUY TẮC GHI CHÚ 3 LẦN RÚT TIỀN ĐẦU TIÊN",
"content": "3 LẦN RÚT TIỀN ĐẦU TIÊN của khách sau khi duyệt cần ghi chú theo format bên dưới:\n\nFormat:\n[1WD / 2WD / 3WD] + [NORMAL hoặc ABNORMAL] + [Lý do nếu ABNORMAL] + [DATE]\n\nVí dụ:\n\n- 1WD + NORMAL + DATE (11/20/2026)\n- 2WD + ABNORMAL + LOW ODDS + DATE (11/20/2026)\n- 3WD + ABNORMAL + INCOMPLETE TURNOVER + DATE (11/20/2026)\n\nCác trạng thái:\n\nNORMAL = Bình thường\nABNORMAL = Bất thường\nLý do bất thường gồm:\n• LOW ODDS = Tỷ lệ thấp\n• ALL IN\n• FIXED LOW BET = Cược cố định số tiền thấp\n• INCOMPLETE TURNOVER = Chưa hoàn thành vòng cược\n• HEAD TO HEAD BETTING = Đánh đối\n\nLưu ý:\n\nNếu khách đã qua lượt duyệt thứ 4 thì xóa ghi chú đi\nKHÔNG áp dụng cách ghi chú này cho khách cũ"
},
{
"title": "QUY TẮC GHI CHÚ KHI TỪ CHỐI LỆNH RÚT TIỀN",
"content": "THÀNH VIÊN ĐẶT CƯỢC TỶ LỆ THẤP , CƯỢC NHỎ : WD ABNORMAL LOW ODDS\nKHÔNG ĐỦ VÒNG CƯỢC : WD ABNORMAL INCOMPLETE TURNOVER\nKHÔNG NẠP ĐỦ ĐIỀU KIỆN RÚT TIỀN THƯỞNG 500 HOẶC TIỀN THƯỞNG NHÓM : WD ABNORMAL Insufficient deposit\nNHẬN THƯỞNG NHÓM ĐƯỜNG TRÙNG IP : WD ABNORMAL SELF-INVITE\n\nĐỐI VỚI NGƯỜI CHƠI CŨ CHỈ GHI CHÚ ĐỐI VỚI NHỮNG NGƯỜI CHƠI CÓ VẤN ĐỀ VỀ CƯỢC HOẶC SỐ DƯ , NHỮNG NGƯỜI CHƠI KHÔNG HOÀN THÀNH VÒNG CƯỢC KHÔNG CẦN PHẢI GHI CHÚ."
},
{
"title": "QUY TẮC KIỀM TRA NHẬN THƯỞNG NHÓM",
"content": "Đối với người chơi nhận thưởng nhóm cần kiểm tra đường dây đại lý có lạm dụng phần thưởng có bình thường hay không:\n⚠️ Đường dây đại lý lạm dụng thưởng đầu\n⚠️ Có liên kết cấp IP và thiết bị với cấp dưới\n⚠️ Kiểm tra ngẫu nhiên 1 2 cấp dưới xem có đặt cược bất thường không\n⛓Nếu người chơi vi phạm 1 trong 3 điều trên thì phần thưởng cần phải khấu trừ và hạn chế tiền thưởng\n⛓ Nếu tất cả đều bình thường và tổng số tiền nạp của người chơi và cấp dưới bằng với tổng số tiền rút thì có thể rút tiền"
},
{
"title": "IFSC AIRP0000001",
"content": "Những Khách có IFSC AIRP0000001 , bên fengkong mình sẽ xuất thử qua 3 lần ( 3 đơn ) , nếu cả 3 lần đều thất bại thì lần thứ 4 thì mình báo cho bên sanfang như vậy , sau đó sanfang xử lý không được yêu càu mình từ chối khách sửa thông tin , thì mình sẽ dùng câu này.\n\nIFSC AIRP0000001 has frequent errors and may cause transaction issues. Please contact Customer Service for assistance."
},
{
"title": "QUY TẮC QUY TRÌNH XỬ LÝ",
"content": "Tối ưu xử lý RÚT TIỀN (15/03/2026)\n\n1️⃣. Thành viên chưa đạt yêu cầu vòng cược (chưa đủ turnover)\n➡️ Quy định xử lý:\nTừ chối rút tiền 3 lần\nNếu hành vi của thành viên vẫn không thay đổi → xử lý theo phương án khấu trừ:\nKhấu trừ toàn bộ lợi nhuận và tiền thưởng, chỉ hoàn trả tiền gốc bằng JCOIN\n\n2️⃣. Thành viên cược tỷ lệ thấp để chạy vòng cược\n✏️ Trường hợp 1:\nThành viên có cược tỷ lệ thấp nhưng không phải tất cả cược đều là tỷ lệ thấp và không phải hành vi chạy vòng cược rõ ràng.\nCó thể từ chối 2–3 lần.\nYêu cầu thành viên tiếp tục cược bình thường.\nNếu sau đó vẫn không thay đổi → Khấu trừ toàn bộ lợi nhuận và tiền thưởng, hoàn trả tiền gốc bằng JCOIN.\n\n✏️ Trường hợp 2:\nThành viên toàn bộ cược đều là tỷ lệ thấp.\nThuộc hành vi vi phạm / chạy vòng cược.\nTrực tiếp khấu trừ toàn bộ lợi nhuận và tiền thưởng, hoàn trả tiền gốc bằng JCOIN.\n\n3️⃣. Thành viên cược All-in (梭哈) / Đối cược (对打)\nTrực tiếp khấu trừ toàn bộ lợi nhuận.\nChỉ hoàn trả tiền gốc (JCOIN).\nNếu hành vi không thay đổi, tiếp tục All-in / Đối cược → Đưa vào danh sách đen (Blacklist).\n\n4️⃣ Kiểm tra rút tiền (Lần 1 – Lần 2 – Lần 3)\nBắt buộc kiểm tra thủ công (manual check).\nKênh quảng cáo (投放): 5 lần vòng cược.\nKhông phải kênh quảng cáo: 8 lần vòng cược.\n\n📌 Lưu ý quan trọng:\nSau mỗi lần kiểm tra, bắt buộc phải ghi chú (remark) vào tài khoản.\nSau khi đã kiểm tra xong lần rút thứ 3, nếu thành viên giao dịch bình thường → xóa ghi chú.\n\n📝 Quy định bổ sung:\nNếu thành viên gửi nhiều yêu cầu rút tiền trong cùng một thời điểm, thì chỉ tính là 1 lần rút tiền."
},
  {
"title": "QUY TRÌNH XỬ LÝ SAI IFSC",
"content": "QUY TRÌNH XỬ LÝ LỆNH RÚT TIỀN SAI IFSC\n\nKhi phát hiện khách hàng nhập sai mã IFSC:\n- Không từ chối (Reject) lệnh rút tiền.\n- Chuyển lệnh sang trạng thái 待审查 (Submit For Review).\n\nSau khi chuyển trạng thái:\n- Pass thông tin vào nhóm.\n- Tag bộ phận CSKH để hỗ trợ khách hàng chỉnh sửa thông tin IFSC.\n\nSau khi CSKH xác nhận đã hoàn tất việc chỉnh sửa:\n- Hậu đài tiến hành đá lệnh về cho khách hàng.\n- Yêu cầu khách tạo lại lệnh rút tiền mới với thông tin đã được cập nhật chính xác.\n\nLưu ý:\n* Tuyệt đối không từ chối lệnh chỉ vì sai mã IFSC.\n* Tất cả các trường hợp sai IFSC đều phải xử lý theo quy trình trên."
}
]
;
